/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.calculator.client;

import com.calculator.common.Constants;
import com.calculator.common.ICalculator;
import com.calculator.common.Result;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Relu
 */
public class CalculatorGUI extends javax.swing.JFrame {

    private class MyMouseAdapter extends MouseAdapter
    {

        @Override
        public void mouseExited(MouseEvent e) 
        {
            JButton button = (JButton) e.getSource();
            button.setBackground(button.getParent().getBackground());
        }

        @Override
        public void mouseEntered(MouseEvent e) 
        {
            JButton button = (JButton) e.getSource();
            button.setBackground(Color.LIGHT_GRAY);
        }
        
    }
    
    private class Operator
    {
        public static final int ADD = 1;
        public static final int SUBTRACT = 2;
        public static final int MULTIPLY = 3;
        public static final int DIVIDE = 4;
        public static final int INVERT = 5;
        public static final int POWER = 6;
        public static final int FACTORIAL = 7;
        public static final int SQRT = 8;

        private final int m_operator;
        private boolean m_wasExecuted;

        Operator(int operator)
        {
            m_operator = operator;
            m_wasExecuted = false;
        }
        public void execute(ICalculator calculator) throws RemoteException 
        {
            switch(m_operator)
            {
                case ADD:
                    calculator.add();
                    break;
                case SUBTRACT:
                    calculator.subtract();
                    break;
                case MULTIPLY:
                    calculator.multiply();
                    break;
                case DIVIDE:
                    calculator.divide();
                    break;
                case INVERT:
                    calculator.invert();
                    break;
                case POWER:
                    calculator.pow();
                    break;
                case FACTORIAL:
                    calculator.factorial();
                    break;
                case SQRT:
                    calculator.sqrt();
                    break;
            }
            
            m_wasExecuted = true;
        }
        
        public int getRequiredOperands()
        {
            if(m_operator == INVERT || m_operator == FACTORIAL || m_operator == SQRT)
                return 1;
            return 2;
        }
        
        public boolean wasExecuted()
        {
            return m_wasExecuted;
        }
            
    }
    
    private final ICalculator m_calculator;
    private Operator m_operator;
    private boolean m_isDotSet;
    private boolean m_shouldErase;
    
    /**
     * Creates new form CalculatorGUI
     * @param calculator
     */
    public CalculatorGUI(ICalculator calculator) {
        m_calculator = calculator;
        m_isDotSet = false;
        m_shouldErase = false;
        
        initComponents();
        setTitle("Calculator");
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        mcButton = new javax.swing.JButton();
        mrButton = new javax.swing.JButton();
        mpButton = new javax.swing.JButton();
        mmButton = new javax.swing.JButton();
        msButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        invertButton = new javax.swing.JButton();
        powButton = new javax.swing.JButton();
        factorialButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        plusMinusButton = new javax.swing.JButton();
        _0Button = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ceButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        _7Button = new javax.swing.JButton();
        _8Button = new javax.swing.JButton();
        _9Button = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        _4Button = new javax.swing.JButton();
        _5Button = new javax.swing.JButton();
        _6Button = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        _1Button = new javax.swing.JButton();
        _2Button = new javax.swing.JButton();
        _3Button = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        expressionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(310, 470));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        displayTextField.setEditable(false);
        displayTextField.setBackground(new java.awt.Color(255, 255, 255));
        displayTextField.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTextField.setText("0");
        getContentPane().add(displayTextField);
        displayTextField.setBounds(10, 40, 289, 49);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 132, 310, 10);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        mcButton.setText("MC");
        mcButton.setBorder(null);
        mcButton.setBorderPainted(false);
        mcButton.setContentAreaFilled(false);
        mcButton.setFocusable(false);
        mcButton.setOpaque(true);
        mcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcButtonActionPerformed(evt);
            }
        });
        mcButton.addMouseListener(myMouseListener);
        jPanel1.add(mcButton);

        mrButton.setText("MR");
        mrButton.setBorder(null);
        mrButton.setBorderPainted(false);
        mrButton.setContentAreaFilled(false);
        mrButton.setFocusable(false);
        mrButton.setOpaque(true);
        mrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrButtonActionPerformed(evt);
            }
        });
        mrButton.addMouseListener(myMouseListener);
        jPanel1.add(mrButton);

        mpButton.setText("M+");
        mpButton.setBorder(null);
        mpButton.setBorderPainted(false);
        mpButton.setContentAreaFilled(false);
        mpButton.setFocusable(false);
        mpButton.setOpaque(true);
        mpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpButtonActionPerformed(evt);
            }
        });
        mpButton.addMouseListener(myMouseListener);
        jPanel1.add(mpButton);

        mmButton.setText("M-");
        mmButton.setBorder(null);
        mmButton.setBorderPainted(false);
        mmButton.setContentAreaFilled(false);
        mmButton.setFocusable(false);
        mmButton.setOpaque(true);
        mmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmButtonActionPerformed(evt);
            }
        });
        mmButton.addMouseListener(myMouseListener);
        jPanel1.add(mmButton);

        msButton.setText("MS");
        msButton.setBorder(null);
        msButton.setBorderPainted(false);
        msButton.setContentAreaFilled(false);
        msButton.setFocusable(false);
        msButton.setOpaque(true);
        msButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msButtonActionPerformed(evt);
            }
        });
        msButton.addMouseListener(myMouseListener);
        jPanel1.add(msButton);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 290, 30);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        invertButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invertButton.setText("1/X");
        invertButton.setBorder(null);
        invertButton.setBorderPainted(false);
        invertButton.setContentAreaFilled(false);
        invertButton.setFocusable(false);
        invertButton.setOpaque(true);
        invertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertButtonActionPerformed(evt);
            }
        });
        invertButton.addMouseListener(myMouseListener);
        jPanel2.add(invertButton);

        powButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        powButton.setText("X^Y");
        powButton.setBorder(null);
        powButton.setBorderPainted(false);
        powButton.setContentAreaFilled(false);
        powButton.setFocusable(false);
        powButton.setOpaque(true);
        powButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButtonActionPerformed(evt);
            }
        });
        powButton.addMouseListener(myMouseListener);
        jPanel2.add(powButton);

        factorialButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        factorialButton.setText("X!");
        factorialButton.setBorder(null);
        factorialButton.setBorderPainted(false);
        factorialButton.setContentAreaFilled(false);
        factorialButton.setFocusable(false);
        factorialButton.setOpaque(true);
        factorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialButtonActionPerformed(evt);
            }
        });
        factorialButton.addMouseListener(myMouseListener);
        jPanel2.add(factorialButton);

        sqrtButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sqrtButton.setText("sqrt(X)");
        sqrtButton.setBorder(null);
        sqrtButton.setBorderPainted(false);
        sqrtButton.setContentAreaFilled(false);
        sqrtButton.setFocusable(false);
        sqrtButton.setOpaque(true);
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });
        sqrtButton.addMouseListener(myMouseListener);
        jPanel2.add(sqrtButton);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 140, 290, 50);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        plusMinusButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        plusMinusButton.setText("\t±");
        plusMinusButton.setBorder(null);
        plusMinusButton.setBorderPainted(false);
        plusMinusButton.setContentAreaFilled(false);
        plusMinusButton.setFocusable(false);
        plusMinusButton.setOpaque(true);
        plusMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusMinusButtonActionPerformed(evt);
            }
        });
        plusMinusButton.addMouseListener(myMouseListener);
        jPanel3.add(plusMinusButton);

        _0Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _0Button.setText("0");
        _0Button.setBorder(null);
        _0Button.setBorderPainted(false);
        _0Button.setContentAreaFilled(false);
        _0Button.setFocusable(false);
        _0Button.setOpaque(true);
        _0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _0ButtonActionPerformed(evt);
            }
        });
        _0Button.addMouseListener(myMouseListener);
        jPanel3.add(_0Button);

        dotButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        dotButton.setText(".");
        dotButton.setBorder(null);
        dotButton.setBorderPainted(false);
        dotButton.setContentAreaFilled(false);
        dotButton.setFocusable(false);
        dotButton.setOpaque(true);
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });
        dotButton.addMouseListener(myMouseListener);
        jPanel3.add(dotButton);

        equalButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        equalButton.setText("=");
        equalButton.setBorder(null);
        equalButton.setBorderPainted(false);
        equalButton.setContentAreaFilled(false);
        equalButton.setFocusable(false);
        equalButton.setOpaque(true);
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });
        equalButton.addMouseListener(myMouseListener);
        jPanel3.add(equalButton);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 390, 290, 50);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        ceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ceButton.setText("CE");
        ceButton.setBorder(null);
        ceButton.setBorderPainted(false);
        ceButton.setContentAreaFilled(false);
        ceButton.setFocusable(false);
        ceButton.setOpaque(true);
        ceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceButtonActionPerformed(evt);
            }
        });
        ceButton.addMouseListener(myMouseListener);
        jPanel4.add(ceButton);

        cButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cButton.setText("C");
        cButton.setBorder(null);
        cButton.setBorderPainted(false);
        cButton.setContentAreaFilled(false);
        cButton.setFocusable(false);
        cButton.setOpaque(true);
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });
        cButton.addMouseListener(myMouseListener);
        jPanel4.add(cButton);

        bButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bButton.setText("B");
        bButton.setBorder(null);
        bButton.setBorderPainted(false);
        bButton.setContentAreaFilled(false);
        bButton.setFocusable(false);
        bButton.setOpaque(true);
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });
        bButton.addMouseListener(myMouseListener);
        jPanel4.add(bButton);

        divideButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        divideButton.setText("/");
        divideButton.setBorder(null);
        divideButton.setBorderPainted(false);
        divideButton.setContentAreaFilled(false);
        divideButton.setFocusable(false);
        divideButton.setOpaque(true);
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });
        divideButton.addMouseListener(myMouseListener);
        jPanel4.add(divideButton);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 190, 290, 50);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        _7Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _7Button.setText("7");
        _7Button.setBorder(null);
        _7Button.setBorderPainted(false);
        _7Button.setContentAreaFilled(false);
        _7Button.setFocusable(false);
        _7Button.setOpaque(true);
        _7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _7ButtonActionPerformed(evt);
            }
        });
        _7Button.addMouseListener(myMouseListener);
        jPanel5.add(_7Button);

        _8Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _8Button.setText("8");
        _8Button.setBorder(null);
        _8Button.setBorderPainted(false);
        _8Button.setContentAreaFilled(false);
        _8Button.setFocusable(false);
        _8Button.setOpaque(true);
        _8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _8ButtonActionPerformed(evt);
            }
        });
        _8Button.addMouseListener(myMouseListener);
        jPanel5.add(_8Button);

        _9Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _9Button.setText("9");
        _9Button.setBorder(null);
        _9Button.setBorderPainted(false);
        _9Button.setContentAreaFilled(false);
        _9Button.setFocusable(false);
        _9Button.setOpaque(true);
        _9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _9ButtonActionPerformed(evt);
            }
        });
        _9Button.addMouseListener(myMouseListener);
        jPanel5.add(_9Button);

        multiplyButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        multiplyButton.setText("*");
        multiplyButton.setBorder(null);
        multiplyButton.setBorderPainted(false);
        multiplyButton.setContentAreaFilled(false);
        multiplyButton.setFocusable(false);
        multiplyButton.setOpaque(true);
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });
        multiplyButton.addMouseListener(myMouseListener);
        jPanel5.add(multiplyButton);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 240, 290, 50);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        _4Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _4Button.setText("4");
        _4Button.setBorder(null);
        _4Button.setBorderPainted(false);
        _4Button.setContentAreaFilled(false);
        _4Button.setFocusable(false);
        _4Button.setOpaque(true);
        _4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4ButtonActionPerformed(evt);
            }
        });
        _4Button.addMouseListener(myMouseListener);
        jPanel6.add(_4Button);

        _5Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _5Button.setText("5");
        _5Button.setBorder(null);
        _5Button.setBorderPainted(false);
        _5Button.setContentAreaFilled(false);
        _5Button.setFocusable(false);
        _5Button.setOpaque(true);
        _5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5ButtonActionPerformed(evt);
            }
        });
        _5Button.addMouseListener(myMouseListener);
        jPanel6.add(_5Button);

        _6Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _6Button.setText("6");
        _6Button.setBorder(null);
        _6Button.setBorderPainted(false);
        _6Button.setContentAreaFilled(false);
        _6Button.setFocusable(false);
        _6Button.setOpaque(true);
        _6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _6ButtonActionPerformed(evt);
            }
        });
        _6Button.addMouseListener(myMouseListener);
        jPanel6.add(_6Button);

        minusButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        minusButton.setText("-");
        minusButton.setBorder(null);
        minusButton.setBorderPainted(false);
        minusButton.setContentAreaFilled(false);
        minusButton.setFocusable(false);
        minusButton.setOpaque(true);
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        minusButton.addMouseListener(myMouseListener);
        jPanel6.add(minusButton);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(10, 290, 290, 50);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        _1Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _1Button.setText("1");
        _1Button.setBorder(null);
        _1Button.setBorderPainted(false);
        _1Button.setContentAreaFilled(false);
        _1Button.setFocusable(false);
        _1Button.setOpaque(true);
        _1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1ButtonActionPerformed(evt);
            }
        });
        _1Button.addMouseListener(myMouseListener);
        jPanel7.add(_1Button);

        _2Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _2Button.setText("2");
        _2Button.setBorder(null);
        _2Button.setBorderPainted(false);
        _2Button.setContentAreaFilled(false);
        _2Button.setFocusable(false);
        _2Button.setOpaque(true);
        _2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2ButtonActionPerformed(evt);
            }
        });
        _2Button.addMouseListener(myMouseListener);
        jPanel7.add(_2Button);

        _3Button.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        _3Button.setText("3");
        _3Button.setBorder(null);
        _3Button.setBorderPainted(false);
        _3Button.setContentAreaFilled(false);
        _3Button.setFocusable(false);
        _3Button.setOpaque(true);
        _3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3ButtonActionPerformed(evt);
            }
        });
        _3Button.addMouseListener(myMouseListener);
        jPanel7.add(_3Button);

        plusButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        plusButton.setText("+");
        plusButton.setBorder(null);
        plusButton.setBorderPainted(false);
        plusButton.setContentAreaFilled(false);
        plusButton.setFocusable(false);
        plusButton.setOpaque(true);
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        plusButton.addMouseListener(myMouseListener);
        jPanel7.add(plusButton);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(10, 340, 290, 50);

        expressionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(expressionLabel);
        expressionLabel.setBounds(14, 10, 280, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        try {
            setOperator(new Operator(Operator.ADD));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_plusButtonActionPerformed

    private void invertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertButtonActionPerformed
        try {
            setOperator(new Operator(Operator.INVERT));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_invertButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        try {
            setOperator(new Operator(Operator.SUBTRACT));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_minusButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        try {
            setOperator(new Operator(Operator.MULTIPLY));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        try {
            setOperator(new Operator(Operator.DIVIDE));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_divideButtonActionPerformed

    private void factorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialButtonActionPerformed
        try {
            setOperator(new Operator(Operator.FACTORIAL));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_factorialButtonActionPerformed

    private void powButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButtonActionPerformed
        try {
            setOperator(new Operator(Operator.POWER));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_powButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        try {
            setOperator(new Operator(Operator.SQRT));
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void setOperator(Operator operator) throws RemoteException 
    {
        if(operator.getRequiredOperands() == 1)
        {
            executeOperator(operator);
        }
        else
        {
            if(m_operator == null)
            {
                m_calculator.setFirstOperand(getDisplayValue());
                m_operator = operator;
                m_shouldErase = true;
            }
            else
            {
                m_calculator.setSecondOperand(getDisplayValue());
                if(!m_operator.wasExecuted())
                    executeOperator(m_operator);
                m_operator = operator;
            }
        }
    }
    
    public double getDisplayValue()
    {
        try
        {
            return Double.parseDouble(displayTextField.getText());
        }
        catch(NumberFormatException e)
        {
            return 0.0;
        }
    }
    
    private void executeOperator(Operator operator) throws RemoteException
    {
        operator.execute(m_calculator);
        m_shouldErase = true;
        
        Result result = m_calculator.getResult();
        if(result.hasNoError())
        {
            m_calculator.setFirstOperand(result.getNumber());
        }
        
        setDisplayValue(result);
    }
    
    private void setDisplayValue(Result result)
    {
        m_shouldErase = true;
        if(result.hasError())
        {
            displayTextField.setText(result.getError());
            m_operator = null;
            m_isDotSet = false;
            try {
                m_calculator.reset();
            } catch (RemoteException ex) {
                Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            String numberString = Double.toString(result.getNumber());
            if(numberString.endsWith(".0"))
                numberString = numberString.substring(0, numberString.length()-2);
            if(numberString.length() > 13)
                numberString = numberString.substring(0, 14);
            
            displayTextField.setText(numberString);
        }
    }
    
    private void addDigit(char digit)
    {
        String currentText = displayTextField.getText();
        
        if(m_shouldErase)
        {
            currentText = "0";
            m_shouldErase = false;
        }
        
        if(currentText.equals("0"))
        {
            if(digit == '.')
                currentText = "0.";
            else
                currentText = "";
        }
        
        currentText += Character.toString(digit);
        displayTextField.setText(currentText);
    }
    
    private void _1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1ButtonActionPerformed
        addDigit('1');
    }//GEN-LAST:event__1ButtonActionPerformed

    private void _2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2ButtonActionPerformed
        addDigit('2');
    }//GEN-LAST:event__2ButtonActionPerformed

    private void _3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3ButtonActionPerformed
        addDigit('3');
    }//GEN-LAST:event__3ButtonActionPerformed

    private void _4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4ButtonActionPerformed
        addDigit('4');
    }//GEN-LAST:event__4ButtonActionPerformed

    private void _5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5ButtonActionPerformed
        addDigit('5');
    }//GEN-LAST:event__5ButtonActionPerformed

    private void _6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__6ButtonActionPerformed
        addDigit('6');
    }//GEN-LAST:event__6ButtonActionPerformed

    private void _7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__7ButtonActionPerformed
        addDigit('7');
    }//GEN-LAST:event__7ButtonActionPerformed

    private void _8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__8ButtonActionPerformed
        addDigit('8');
    }//GEN-LAST:event__8ButtonActionPerformed

    private void _9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__9ButtonActionPerformed
        addDigit('9');
    }//GEN-LAST:event__9ButtonActionPerformed

    private void _0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__0ButtonActionPerformed
        addDigit('0');
    }//GEN-LAST:event__0ButtonActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        if(!m_isDotSet)
        {
            addDigit('.');
            m_isDotSet = true;
        }
    }//GEN-LAST:event_dotButtonActionPerformed

    private void plusMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusMinusButtonActionPerformed
        String currentText = displayTextField.getText();
        if(currentText.equals("0"))
            return;
        
        if(currentText.startsWith("-"))
            currentText = currentText.substring(1);
        else
            currentText = "-" + currentText;
        displayTextField.setText(currentText);
    }//GEN-LAST:event_plusMinusButtonActionPerformed

    private void ceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceButtonActionPerformed
        displayTextField.setText("0");
        m_shouldErase = false;
        m_isDotSet = false;
    }//GEN-LAST:event_ceButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        displayTextField.setText("0");
        m_operator = null;
        m_shouldErase = false;
        m_isDotSet = false;
        try {
            m_calculator.reset();
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        m_shouldErase = false;
        if(getDisplayValue() == 0.0)
        {
            displayTextField.setText("0");
            return;
        }
        
        String currentText = displayTextField.getText();
        String newText = (currentText.length() == 1) ? "0" : currentText.substring(0, currentText.length()-1);
        if(currentText.charAt(currentText.length()-1) == '.')
        {
            m_isDotSet = false;
        }
        displayTextField.setText(newText);
    }//GEN-LAST:event_bButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
        try {
            if(m_operator == null)
                return;
            
            if(!m_operator.wasExecuted())
                m_calculator.setSecondOperand(getDisplayValue());
            executeOperator(m_operator);
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_equalButtonActionPerformed

    private void mcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcButtonActionPerformed
        try {
            throw new RemoteException();
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mcButtonActionPerformed

    private void mrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrButtonActionPerformed
        try {
throw new RemoteException();
            
            
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mrButtonActionPerformed

    private void msButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msButtonActionPerformed
        try {
            throw new RemoteException();
            
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_msButtonActionPerformed

    private void mpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpButtonActionPerformed
        try {
            throw new RemoteException();
            
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mpButtonActionPerformed

    private void mmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmButtonActionPerformed
        try {
            throw new RemoteException();
            
        } catch (RemoteException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mmButtonActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        switch(evt.getKeyChar())
        {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                addDigit(evt.getKeyChar());
                break;
            case '+':
                plusButtonActionPerformed(null);
                break;
            case '-':
                minusButtonActionPerformed(null);
                break;
            case '*':
                multiplyButtonActionPerformed(null);
                break;
            case '/':
                divideButtonActionPerformed(null);
                break;
            case '\n':
                equalButtonActionPerformed(null);
                break;
            case '\b':
                bButtonActionPerformed(null);
                break;
        }
    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registry registry;
                ICalculator calculator = null;
                try {
                    registry = LocateRegistry.getRegistry("localhost", Constants.PORT);
                    calculator = (ICalculator) registry.lookup(Constants.CALCULATOR_NAME);
                } catch (RemoteException ex) {
                    Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                new CalculatorGUI(calculator).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _0Button;
    private javax.swing.JButton _1Button;
    private javax.swing.JButton _2Button;
    private javax.swing.JButton _3Button;
    private javax.swing.JButton _4Button;
    private javax.swing.JButton _5Button;
    private javax.swing.JButton _6Button;
    private javax.swing.JButton _7Button;
    private javax.swing.JButton _8Button;
    private javax.swing.JButton _9Button;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.JButton ceButton;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JLabel expressionLabel;
    private javax.swing.JButton factorialButton;
    private javax.swing.JButton invertButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mcButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton mmButton;
    private javax.swing.JButton mpButton;
    private javax.swing.JButton mrButton;
    private javax.swing.JButton msButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton plusMinusButton;
    private javax.swing.JButton powButton;
    private javax.swing.JButton sqrtButton;
    // End of variables declaration//GEN-END:variables
    private final MyMouseAdapter myMouseListener = new MyMouseAdapter();
}